# Generated by Django 6.0 on 2025-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInput',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('count', models.FloatField(blank=True, db_column='COUNT', null=True)),
                ('use_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farm_input',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmOrder',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='待发货', max_length=10)),
            ],
            options={
                'db_table': 'farm_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='地块编号')),
                ('area', models.FloatField(verbose_name='面积(亩)')),
                ('soil', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('free', '空闲'), ('planted', '已种植'), ('maintenance', '维护中')], default='free', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '农田地块',
                'verbose_name_plural': '农田地块',
                'db_table': 'farm_plot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(max_length=20)),
                ('plant_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('record_status', models.CharField(default='生长中', max_length=10)),
            ],
            options={
                'db_table': 'planting_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.FloatField(verbose_name='温度')),
                ('humidity', models.FloatField(verbose_name='湿度')),
                ('soil_moisture', models.FloatField(verbose_name='土壤水分')),
                ('light', models.FloatField(verbose_name='光照强度')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=20)),
                ('role', models.CharField(default='员工', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
    ]
